---
- name: Install apt-transport-https
  shell: apt-get install apt-transport-https -y --force-yes
  args:
    warn: no

- name: Add Confluent Apt Key
  apt_key:
    url: "{{confluent_common.repository.debian.key_url}}"
    state: present
  when: not custom_apt_repo|bool

- name: Add Confluent Apt Repo
  apt_repository:
    repo: "{{confluent_common.repository.debian.repository}}"
    state: present
  when: not custom_apt_repo|bool

- name: Add Custom Apt Repo
  copy:
    src: "{{custom_apt_repo_filepath}}"
    dest: /etc/apt/sources.list.d/custom_confluent.list
  when: custom_apt_repo|bool
  notify:
    - apt-get update

- meta: flush_handlers

- name: Copy in repo skip valid check
  copy:
    content: 'Acquire::Check-Valid-Until "0";'
    dest: /etc/apt/apt.conf.d/skip-check
  notify:
    - debian apt-get update
  when:
    - install_java|bool
    - not custom_apt_repo|bool

- name: Add jessie-backports Repo
  lineinfile:
    path: /etc/apt/sources.list
    line: deb [check-valid-until=no] http://archive.debian.org/debian jessie-backports main
    regexp: '.*jessie-backports.*'
  notify:
    - debian apt-get update
  when:
    - install_java|bool
    - not custom_apt_repo|bool
    - ansible_distribution_release == "jessie"

- name: Add stretch-backports Repo
  lineinfile:
    path: /etc/apt/sources.list
    line: deb [check-valid-until=no] http://ftp.debian.org/debian stretch-backports main
    regexp: '.*stretch-backports.*'
  notify:
    - debian apt-get update
  when:
    - install_java|bool
    - not custom_apt_repo|bool
    - ansible_distribution_release == "stretch"

- meta: flush_handlers

- name: Install Java - jessie
  apt:
    name: "{{ debian_java_package_name }}"
    state: present
    default_release: jessie-backports
  when:
    - install_java|bool
    - not custom_apt_repo|bool
    - ansible_distribution_release == "jessie"

- name: Install Java - stretch
  apt:
    name: "{{ debian_java_package_name }}"
    state: present
    default_release: stretch-backports
  when:
    - install_java|bool
    - not custom_apt_repo|bool
    - ansible_distribution_release == "stretch"

- name: Install Java (Custom Repo)
  apt:
    name: "{{ debian_java_package_name }}"
    state: present
  when:
    - install_java|bool
    - custom_apt_repo|bool

- name: Install rsync
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - rsync
    - ca-certificates
